version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  eureka-server:
    image: telemetry/eureka-server:1.0.0-SNAPSHOT
    expose:
    - "8761"
    depends_on:
    - kafka

  zuul-server:
    image: telemetry/zuul-server:1.0.0-SNAPSHOT
    ports:
    - "8762:8762"
    depends_on:
    - eureka-server

  data-storage-service:
    image: telemetry/data-storage-service:1.0.0-SNAPSHOT
    expose:
    - "1-65535"
    depends_on:
    - zuul-server

  data-receiver-service:
    image: telemetry/data-receiver-service:1.0.0-SNAPSHOT
    expose:
    - "1-65535"
    depends_on:
    - data-storage-service