version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    networks:
      - telemetry-network

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    expose:
      - "9092"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - telemetry-network

  eureka-server:
    image: telemetry/eureka-server:1.0.0-SNAPSHOT
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - telemetry-network

  zuul-server:
    image: telemetry/zuul-server:1.0.0-SNAPSHOT
    expose:
      - "8762"
    ports:
      - "8762:8762"
    depends_on:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - telemetry-network

  data-storage-service:
    image: telemetry/data-storage-service:1.0.0-SNAPSHOT
    expose:
      - "1212"
    depends_on:
      - kafka
      - zuul-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      KAFKA_HOST_PORT: kafka:9092
      SERVER_PORT: 1212
    networks:
      - telemetry-network

  data-receiver-service:
    image: telemetry/data-receiver-service:1.0.0-SNAPSHOT
    expose:
      - "1212"
    depends_on:
      - kafka
      - data-storage-service
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      KAFKA_HOST_PORT: kafka:9092
      SERVER_PORT: 1212
    networks:
      - telemetry-network

networks:
  telemetry-network:
    driver: bridge