spring:
  application:
    name: data-storage-service

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

kafka:
  servers:
    config: 127.0.0.1:9092
  topic: TTelemetry
